trigger:
- none

pool:
  name: irfank
  
steps:
- task: FortifySCA@7
  inputs:
    applicationType: 'java'
    buildToolOptions: 'gradlew build'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyApplicationName: 'deneme'
    fortifyApplicationVersion: 'kotlin'
