trigger:
- none

pool:
  name: irfank
  
steps:
- task: FortifySCA@7
  inputs:
    applicationType: 'java'
    buildSourceVersion: '17'
    buildAnalyzerParams: 'gradlew build'
    fortifyBuildId: 'test2'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'fortifyssc'
    fortifyApplicationName: 'deneme'
    fortifyApplicationVersion: 'kotlin'
