trigger:
- none

pool:
  name: irfank
  
steps:
- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    buildAnalyzerParams: 'msbuild /t:rebuild'
    fortifyBuildId: 'test2'
    scaVerbose: true
    scaDebug: true
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'fortifyssc'
    fortifyApplicationName: 'deneme'
    fortifyApplicationVersion: 'kotlin'
