trigger:
- none

pool:
  name: irfank
  
steps:
- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    buildToolOptions: 'msbuild /t:rebuild'
    fortifySourceTranslate: 'RichesDotnetApp.sln'
    fortifyBuildId: 'test2'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'fortifyssc'
    fortifyApplicationName: 'deneme'
    fortifyApplicationVersion: 'kotlin'
